export const initialRecipes = [
    'Hydrogen + Oxygen',
    'Carbon + Oxygen',
    'Sodium + Chlorine',
    'Iron + Oxygen',
    'Copper + Oxygen',
    'Aluminum + Oxygen',
    'Gold + Aqua Regia',
    'Silver + Nitric Acid',
    'Zinc + Sulfuric Acid',
    'Magnesium + Hydrochloric Acid',
    'Tin + Lead',
    'Nickel + Hydrogen',
    'Platinum + Hydrogen Peroxide',
    'Titanium + Chlorine',
    'Mercury + Sulfur',
    'Uranium + Neutron',
    'Potassium + Water',
];

export const basicReactions = {
    "Hydrogen + Oxygen": { result: "Water", emoji: "💧" },
    "Carbon + Oxygen": { result: "CarbonDioxide", emoji: "☁️" },
    "Sodium + Chlorine": { result: "Salt", emoji: "🧂" },
    "Iron + Oxygen": { result: "IronOxide", emoji: "🔴" },
    "Copper + Oxygen": { result: "CopperOxide", emoji: "🟠" },
    "Aluminum + Oxygen": { result: "AluminumOxide", emoji: "⚪" },
    "Gold + Aqua Regia": { result: "GoldChloride", emoji: "🟡" },
    "Silver + Nitric Acid": { result: "SilverNitrate", emoji: "🔵" },
    "Zinc + Sulfuric Acid": { result: "ZincSulfate", emoji: "🟢" },
    "Magnesium + Hydrochloric Acid": { result: "MagnesiumChloride", emoji: "🟣" },
    "Tin + Lead": { result: "Solder", emoji: "🔩" },
    "Nickel + Hydrogen": { result: "NickelHydride", emoji: "⚙️" },
    "Platinum + Hydrogen Peroxide": { result: "PlatinumOxide", emoji: "⚗️" },
    "Titanium + Chlorine": { result: "TitaniumChloride", emoji: "🔷" },
    "Mercury + Sulfur": { result: "MercurySulfide", emoji: "🟤" },
    "Uranium + Neutron": { result: "UraniumIsotope", emoji: "☢️" },
    "Potassium + Water": { result: "PotassiumHydroxide", emoji: "🧪" },
};