import {ref} from 'vue'
import {defineStore} from 'pinia'
import {useLocalStorage} from "@vueuse/core";

export interface ResourceStoreEntry {
    title: string
    emoji: string
}

export const useResourcesStore = defineStore('resources', () => {
    const resources =
        useLocalStorage<ResourceStoreEntry[]>('chemcraft/resources', [ 
            {title: 'Hydrogen',     emoji: '🔵'}, 
            {title: 'Helium',       emoji: '🎈'},
            {title: 'Lithium',      emoji: '⚡️'}, 
            {title: 'Beryllium',    emoji: '🟢'}, 
            {title: 'Boron',        emoji: '🛡️'},
            {title: 'Carbon',       emoji: '💎'}, 
            {title: 'Nitrogen',     emoji: '🌿'}, 
            {title: 'Oxygen',       emoji: '🔥'}, 
            {title: 'Fluorine',     emoji: '🦷'}, 
            //{title: 'Neon',         emoji: '💡'}, 
            {title: 'Sodium',       emoji: '🔋'}, 
            {title: 'Magnesium',    emoji: '✨'}, 
            {title: 'Aluminium',    emoji: '✈️'}, 
            {title: 'Silicon',      emoji: '💻'}, 
            {title: 'Phosphorus',   emoji: '💨'}, 
            {title: 'Sulfur',       emoji: '🟨'}, 
            {title: 'Chlorine',     emoji: '🧪'}, 
            {title: 'Argon',        emoji: '🟣'}, 
            {title: 'Potassium',    emoji: '🍌'}, 
            {title: 'Calcium',      emoji: '🦴'},   
            //{title: 'Scandium',     emoji: '🛠️'},   
            {title: 'Titanium',     emoji: '🦾'},   
            {title: 'Vanadium',     emoji: '🔧'},
            {title: 'Chromium',     emoji: '✨'},
            {title: 'Manganese',    emoji: '⚙️'},
            {title: 'Iron',         emoji: '🪨'},
            {title: 'Cobalt',       emoji: '🟦'},
            {title: 'Nickel',       emoji: '🪙'},
            {title: 'Copper',       emoji: '⚱️'},
            {title: 'Zinc',         emoji: '⚡'},
            {title: 'Gallium',      emoji: '🌡'},
            //{title: 'Germanium',    emoji: '🪨'},
            //{title: 'Arsenic',      emoji: '🪨'},
            //{title: 'Selenium',     emoji: '🪨'},
            //{title: 'Bromine',      emoji: '🪨'},
            //{title: 'Krypton',      emoji: '🪨'},
            //{title: 'Rubidium',     emoji: '🪨'},
            //{title: 'Strontium',    emoji: '🪨'},
            {title: 'Yttrium',      emoji: '🔧'}, 
            {title: 'Zirconium',    emoji: '⚙️'}, 
            {title: 'Niobium',      emoji: '🔩'},
            {title: 'Molybdenum',   emoji: '🔥'}, 
            //{title: 'Technetium',   emoji: '🪨'},
            //{title: 'Ruthenium',    emoji: '🪨'},
            //{title: 'Rhodium',      emoji: '🪨'},
            {title: 'Palladium',    emoji: '💍'}, 
            {title: 'Silver',       emoji: '🥈'}, 
            {title: 'Cadmium',      emoji: '⚠️'}, 
            {title: 'Indium',       emoji: '📱'}, 
            {title: 'Tin',          emoji: '🥫'}, 
            {title: 'Antimony',     emoji: '⚖️'}, 
            //{title: 'Tellurium',    emoji: '🪨'},
            {title: 'Iodine',       emoji: '🧂'},
            //{title: 'Xenon',        emoji: '🪨'},
            {title: 'Caesium',      emoji: '⏰'},
            {title: 'Barium',       emoji: '🩻'},
            //{title: 'Lanthanum',    emoji: '🪨'},
            //{title: 'Cerium',       emoji: '🪨'},
            //{title: 'Praseodymium', emoji: '🪨'},
            {title: 'Neodymium',    emoji: '🧲'},
            //{title: 'Samarium',     emoji: '🪨'},
            //{title: 'Europium',     emoji: '🪨'},
            //{title: 'Gadolinium',   emoji: '🪨'},
            //{title: 'Terbium',      emoji: '🪨'},
            //{title: 'Dysprosium',   emoji: '🪨'},
            //{title: 'Holmium',      emoji: '🪨'},
            //{title: 'Erbium',       emoji: '🪨'},
            //{title: 'Thulium',      emoji: '🪨'},
            //{title: 'Ytterbium',    emoji: '🪨'},
            //{title: 'Lutetium',     emoji: '🪨'},
            //{title: 'Hafnium',      emoji: '🪨'},
            //{title: 'Tantalum',     emoji: '🪨'},
            {title: 'Tungsten',     emoji: '💡'},
            //{title: 'Rhenium',      emoji: '🪨'},
            {title: 'Osmium',       emoji: '🔗'}, 
            {title: 'Iridium',      emoji: '🚀'}, 
            {title: 'Platinum',     emoji: '👑'}, 
            {title: 'Gold',         emoji: '🏆'}, 
            //{title: 'Thallium',     emoji: '🪨'},
            {title: 'Lead',         emoji: '⚫'},
            {title: 'Bismuth',      emoji: '🌈'},
            //{title: 'Polonium',     emoji: '🪨'},
            //{title: 'Astatine',     emoji: '🪨'},
            {title: 'Radon',        emoji: '🟣'},
            //{title: 'Francium',     emoji: '🪨'},
            //{title: 'Radium',       emoji: '🪨'},
            //{title: 'Actinium',     emoji: '🪨'},
            //{title: 'Thorium',      emoji: '🪨'},
            //{title: 'Protactinium', emoji: '🪨'},
            {title: 'Uranium',      emoji: '☢️'},
            //{title: 'Neptunium',    emoji: '🪨'},
            //{title: 'Plutonium',    emoji: '🪨'},
            //{title: 'Americium',    emoji: '🪨'},
            //{title: 'Curium',       emoji: '🪨'},
            //{title: 'Berkelium',    emoji: '🪨'},
            //{title: 'Californium',  emoji: '🪨'},
            //{title: 'Einsteinium',  emoji: '🪨'},
            //{title: 'Fermium',      emoji: '🪨'},
            //{title: 'Mendelevium',  emoji: '🪨'},
            //{title: 'Nobelium',     emoji: '🪨'},
            //{title: 'Lawrencium',   emoji: '🪨'},
            //{title: 'Rutherfordium', emoji: '🪨'},
            //{title: 'Dubnium',      emoji: '🪨'},
            //{title: 'Seaborgium',   emoji: '🪨'},
            //{title: 'Bohrium',      emoji: '🪨'},
            //{title: 'Hassium',      emoji: '🪨'},
            //{title: 'Meitnerium',   emoji: '🪨'},
            //{title: 'Darmstadtium', emoji: '🪨'},
            //{title: 'Roentgenium',  emoji: '🪨'},
            //{title: 'Copernicium',  emoji: '🪨'},
            //{title: 'Nihonium',     emoji: '🪨'},
            //{title: 'Flerovium',    emoji: '🪨'},
            //{title: 'Moscovium',    emoji: '🪨'},
            //{title: 'Livermorium',  emoji: '🪨'},
            //{title: 'Tennessine',   emoji: '🪨'},
            //{title: 'Oganesson',    emoji: '🪨'},
    ]);
    function addResource(box: ResourceStoreEntry) {
        resources.value.push(box)
    }

    return { resources, addResource}
})

